services:
  postgres:
    image: postgres:latest
    container_name: url-shortener-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: url-shortener-db
    ports:
      - "5432:5432"