spring:
  application:
    name: url-shortener

  datasource:
    url: jdbc:postgresql://postgres:5432/url-shortener-db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key
  issuer: task-manager
  expires-in: 300

admin:
  credentials:
    username: admin
    password: admin